/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiffinRouteImport } from './routes/tiffin'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as OrderTrackingOrderIdRouteImport } from './routes/order-tracking.$orderId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSpecialsRouteImport } from './routes/admin/specials'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminFloorRouteImport } from './routes/admin/floor'
import { Route as AdminCateringRouteImport } from './routes/admin/catering'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAddonsRouteImport } from './routes/admin/addons'

const TiffinRoute = TiffinRouteImport.update({
  id: '/tiffin',
  path: '/tiffin',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrderTrackingOrderIdRoute = OrderTrackingOrderIdRouteImport.update({
  id: '/order-tracking/$orderId',
  path: '/order-tracking/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpecialsRoute = AdminSpecialsRouteImport.update({
  id: '/specials',
  path: '/specials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFloorRoute = AdminFloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCateringRoute = AdminCateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddonsRoute = AdminAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/menu': typeof MenuRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/tiffin': typeof TiffinRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/floor': typeof AdminFloorRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-tracking/$orderId': typeof OrderTrackingOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/menu': typeof MenuRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/tiffin': typeof TiffinRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/floor': typeof AdminFloorRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-tracking/$orderId': typeof OrderTrackingOrderIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catering': typeof CateringRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/menu': typeof MenuRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
  '/tiffin': typeof TiffinRoute
  '/admin/addons': typeof AdminAddonsRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/catering': typeof AdminCateringRoute
  '/admin/floor': typeof AdminFloorRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/specials': typeof AdminSpecialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/order-tracking/$orderId': typeof OrderTrackingOrderIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/menu'
    | '/privacy-policy'
    | '/terms'
    | '/tiffin'
    | '/admin/addons'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/catering'
    | '/admin/floor'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/specials'
    | '/admin/users'
    | '/order-tracking/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/menu'
    | '/privacy-policy'
    | '/terms'
    | '/tiffin'
    | '/admin/addons'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/catering'
    | '/admin/floor'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/specials'
    | '/admin/users'
    | '/order-tracking/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catering'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/menu'
    | '/privacy-policy'
    | '/terms'
    | '/tiffin'
    | '/admin/addons'
    | '/admin/billing'
    | '/admin/categories'
    | '/admin/catering'
    | '/admin/floor'
    | '/admin/kitchen'
    | '/admin/login'
    | '/admin/menu'
    | '/admin/settings'
    | '/admin/specials'
    | '/admin/users'
    | '/order-tracking/$orderId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CateringRoute: typeof CateringRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  MenuRoute: typeof MenuRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
  TiffinRoute: typeof TiffinRoute
  OrderTrackingOrderIdRoute: typeof OrderTrackingOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tiffin': {
      id: '/tiffin'
      path: '/tiffin'
      fullPath: '/tiffin'
      preLoaderRoute: typeof TiffinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/order-tracking/$orderId': {
      id: '/order-tracking/$orderId'
      path: '/order-tracking/$orderId'
      fullPath: '/order-tracking/$orderId'
      preLoaderRoute: typeof OrderTrackingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/specials': {
      id: '/admin/specials'
      path: '/specials'
      fullPath: '/admin/specials'
      preLoaderRoute: typeof AdminSpecialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/floor': {
      id: '/admin/floor'
      path: '/floor'
      fullPath: '/admin/floor'
      preLoaderRoute: typeof AdminFloorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catering': {
      id: '/admin/catering'
      path: '/catering'
      fullPath: '/admin/catering'
      preLoaderRoute: typeof AdminCateringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/addons': {
      id: '/admin/addons'
      path: '/addons'
      fullPath: '/admin/addons'
      preLoaderRoute: typeof AdminAddonsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddonsRoute: typeof AdminAddonsRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCateringRoute: typeof AdminCateringRoute
  AdminFloorRoute: typeof AdminFloorRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSpecialsRoute: typeof AdminSpecialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddonsRoute: AdminAddonsRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCateringRoute: AdminCateringRoute,
  AdminFloorRoute: AdminFloorRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSpecialsRoute: AdminSpecialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CateringRoute: CateringRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  MenuRoute: MenuRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
  TiffinRoute: TiffinRoute,
  OrderTrackingOrderIdRoute: OrderTrackingOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
